timeout 1
default postmarketOS
menu title boot prev kernel

label postmarketOS
	kernel /vmlinuz
	fdt /msm8916-oppo-a37.dtb
	initrd /initramfs
	append console=tty0 console=ttyMSM0,115200 earlycon pmos_boot_uuid=91821e92-5846-4f8d-bcaf-1699efadb18b pmos_root_uuid=986a0f2b-090a-4878-b000-3a257f2c7613 pmos_rootfsopts=defaults
