Define {
	WcdPlaybackPCM "hw:${CardId},0"
	WcdCapturePCM "hw:${CardId},1"
}
<platforms/msm8916/qdsp6-components.conf>

SectionDevice."Speaker" {
	Comment "Speaker playback"

	ConflictingDevice [
		"Headphones"
		"Earpiece"
	]

	EnableSequence [
		cset "name='Speaker Switch' 1"
		cset "name='HPHL' 1"
		cset "name='HPHR' 1"
		cset "name='EAR_S' 0"
		cset "name='RX1 MIX1 INP1' RX1"
		cset "name='RX1 MIX1 INP2' RX2"
		cset "name='RX1 Digital Volume' 84"
		cset "name='RX2 Digital Volume' 84"
	]

	DisableSequence [
		cset "name='Speaker Switch' 0"
		cset "name='HPHL' 0"
		cset "name='HPHR' 0"
		cset "name='RX1 Digital Volume' 0"
		cset "name='RX2 Digital Volume' 0"
		cset "name='RX1 MIX1 INP1' ZERO"
		cset "name='RX1 MIX1 INP2' ZERO"
	]

	Value {
		PlaybackPCM "${var:WcdPlaybackPCM}"
		PlaybackChannels 2
		PlaybackPriority 200
	}
}

SectionDevice."Earpiece" {
	Comment "Earpiece playback"

	ConflictingDevice [
		"Headphones"
		"Speaker"
	]

	EnableSequence [
		cset "name='Speaker Switch' 0"
		cset "name='HPHL' 0"
		cset "name='HPHR' 0"
		cset "name='RX1 MIX1 INP1' RX1"
		cset "name='RX1 MIX1 INP2' RX2"
		cset "name='RDAC2 MUX' RX1"
		cset "name='EAR_S' 1"
		cset "name='RX1 Digital Volume' 84"
		cset "name='RX2 Digital Volume' 84"
	]

	DisableSequence [
		cset "name='RX1 Digital Volume' 0"
		cset "name='RX2 Digital Volume' 0"
		cset "name='EAR_S' 0"
		cset "name='RX1 MIX1 INP1' ZERO"
		cset "name='RX1 MIX1 INP2' ZERO"
	]

	Value {
		PlaybackPCM "${var:WcdPlaybackPCM}"
		PlaybackChannels 2
		PlaybackPriority 100
	}
}

<codecs/msm8916-wcd/Headphones.conf>
<codecs/msm8916-wcd/PrimaryMic.conf>
<codecs/msm8916-wcd/HeadsetMic.conf>
